export interface Strategy {
  id: string;
  name: string;
  cls: 'metals' | 'forex' | 'indices' | 'commodities';
  tagCls: string;
  tagLabel: string;
  risk: number;
  color: string;
  desc: string;
  ytd: string;
  ytdN: number;
  allTime: string;
  monthAvg: string;
  maxDD: number;
  sharpe: number;
  winRate: number;
  avgWin: string;
  avgLoss: string;
  profitFactor: number;
  totalTrades: number;
  avgHold: string;
  invested?: boolean;
  investedAmount?: string;
  since: string;
}

export const strategies: Strategy[] = [
  {
    id: 'I',
    name: 'Aurum Momentum',
    cls: 'metals',
    tagCls: 'tag-metals',
    tagLabel: 'Metals',
    risk: 2,
    color: '#d4af37',
    desc: 'Momentum-driven gold and silver futures strategy using systematic price-action signals with volume confirmation. Position sizing is strictly proportional to account equity, with no overnight exposure above defined thresholds. Delivers consistent performance across both trending and ranging precious metals market conditions.',
    ytd: '+28.4%',
    ytdN: 28.4,
    allTime: '+187.3%',
    monthAvg: '+2.1%',
    maxDD: -8.2,
    sharpe: 2.4,
    winRate: 64,
    avgWin: '+2.8%',
    avgLoss: '-1.4%',
    profitFactor: 2.8,
    totalTrades: 142,
    avgHold: '3.2d',
    invested: true,
    investedAmount: '$28,000',
    since: 'Jan 2022'
  },
  {
    id: 'II',
    name: 'Argentum Scalper',
    cls: 'metals',
    tagCls: 'tag-metals',
    tagLabel: 'Metals',
    risk: 3,
    color: '#d4af37',
    desc: 'High-frequency silver scalping strategy targeting micro-movements in spot silver markets. Uses advanced order flow analysis and sub-second execution timing. Designed for consistent small gains with tight risk management and rapid position turnover.',
    ytd: '+34.2%',
    ytdN: 34.2,
    allTime: '+156.8%',
    monthAvg: '+2.8%',
    maxDD: -12.4,
    sharpe: 2.1,
    winRate: 58,
    avgWin: '+1.2%',
    avgLoss: '-0.8%',
    profitFactor: 2.3,
    totalTrades: 487,
    avgHold: '0.8d',
    since: 'Mar 2022'
  },
  {
    id: 'III',
    name: 'EUR/USD Precision',
    cls: 'forex',
    tagCls: 'tag-forex',
    tagLabel: 'Forex',
    risk: 2,
    color: '#9ec8ff',
    desc: 'Systematic EUR/USD trading strategy based on multi-timeframe trend analysis and key support/resistance levels. Combines technical indicators with fundamental bias to capture medium-term directional moves with favorable risk-reward ratios.',
    ytd: '+19.6%',
    ytdN: 19.6,
    allTime: '+94.3%',
    monthAvg: '+1.6%',
    maxDD: -6.8,
    sharpe: 2.7,
    winRate: 62,
    avgWin: '+2.4%',
    avgLoss: '-1.2%',
    profitFactor: 3.1,
    totalTrades: 98,
    avgHold: '5.4d',
    invested: true,
    investedAmount: '$32,000',
    since: 'May 2022'
  },
  {
    id: 'IV',
    name: 'GBP/JPY Volatility',
    cls: 'forex',
    tagCls: 'tag-forex',
    tagLabel: 'Forex',
    risk: 4,
    color: '#9ec8ff',
    desc: 'Aggressive volatility-based strategy targeting GBP/JPY breakouts during high-impact news events and session overlaps. Employs dynamic position sizing based on ATR and captures explosive moves with trailing stops.',
    ytd: '+42.8%',
    ytdN: 42.8,
    allTime: '+203.4%',
    monthAvg: '+3.4%',
    maxDD: -18.6,
    sharpe: 1.8,
    winRate: 52,
    avgWin: '+4.2%',
    avgLoss: '-2.8%',
    profitFactor: 1.9,
    totalTrades: 156,
    avgHold: '2.1d',
    since: 'Feb 2022'
  },
  {
    id: 'V',
    name: 'S&P 500 Trend',
    cls: 'indices',
    tagCls: 'tag-indices',
    tagLabel: 'Indices',
    risk: 2,
    color: '#c8b4ff',
    desc: 'Long-term trend-following strategy on S&P 500 futures using moving average crossovers and momentum confirmation. Designed to capture major market trends while filtering out noise with adaptive position sizing.',
    ytd: '+16.2%',
    ytdN: 16.2,
    allTime: '+78.9%',
    monthAvg: '+1.3%',
    maxDD: -9.4,
    sharpe: 2.2,
    winRate: 48,
    avgWin: '+5.8%',
    avgLoss: '-2.4%',
    profitFactor: 2.6,
    totalTrades: 42,
    avgHold: '18.6d',
    invested: true,
    investedAmount: '$26,000',
    since: 'Apr 2022'
  },
  {
    id: 'VI',
    name: 'NASDAQ Momentum',
    cls: 'indices',
    tagCls: 'tag-indices',
    tagLabel: 'Indices',
    risk: 3,
    color: '#c8b4ff',
    desc: 'Tech-focused momentum strategy trading NASDAQ-100 futures with emphasis on capturing strong directional moves. Uses relative strength analysis and volume patterns to identify high-probability setups.',
    ytd: '+24.8%',
    ytdN: 24.8,
    allTime: '+142.6%',
    monthAvg: '+2.0%',
    maxDD: -14.2,
    sharpe: 1.9,
    winRate: 56,
    avgWin: '+3.8%',
    avgLoss: '-2.2%',
    profitFactor: 2.4,
    totalTrades: 87,
    avgHold: '6.8d',
    since: 'Jan 2022'
  },
  {
    id: 'VII',
    name: 'Crude Oil Range',
    cls: 'commodities',
    tagCls: 'tag-commodities',
    tagLabel: 'Commodities',
    risk: 3,
    color: '#d4af37',
    desc: 'Mean-reversion strategy trading WTI crude oil within established ranges. Identifies overbought/oversold conditions using oscillators and supply/demand zones for high-probability reversal trades.',
    ytd: '+21.4%',
    ytdN: 21.4,
    allTime: '+118.7%',
    monthAvg: '+1.7%',
    maxDD: -11.8,
    sharpe: 2.0,
    winRate: 60,
    avgWin: '+2.6%',
    avgLoss: '-1.6%',
    profitFactor: 2.7,
    totalTrades: 124,
    avgHold: '4.2d',
    since: 'Mar 2022'
  },
  {
    id: 'VIII',
    name: 'Natural Gas Breakout',
    cls: 'commodities',
    tagCls: 'tag-commodities',
    tagLabel: 'Commodities',
    risk: 4,
    color: '#d4af37',
    desc: 'Breakout-focused strategy on natural gas futures targeting seasonal patterns and weather-driven volatility. Combines fundamental analysis with technical breakout signals for explosive profit potential.',
    ytd: '+38.6%',
    ytdN: 38.6,
    allTime: '+189.2%',
    monthAvg: '+3.1%',
    maxDD: -16.4,
    sharpe: 1.7,
    winRate: 54,
    avgWin: '+5.2%',
    avgLoss: '-3.4%',
    profitFactor: 2.1,
    totalTrades: 96,
    avgHold: '3.8d',
    since: 'Feb 2022'
  },
  {
    id: 'IX',
    name: 'Palladium Swing',
    cls: 'metals',
    tagCls: 'tag-metals',
    tagLabel: 'Metals',
    risk: 3,
    color: '#d4af37',
    desc: 'Swing trading strategy focused on palladium futures, capitalizing on industrial demand cycles and supply constraints. Uses multi-day position holds with technical and fundamental confluence.',
    ytd: '+26.8%',
    ytdN: 26.8,
    allTime: '+134.2%',
    monthAvg: '+2.2%',
    maxDD: -10.6,
    sharpe: 2.3,
    winRate: 58,
    avgWin: '+4.2%',
    avgLoss: '-2.4%',
    profitFactor: 2.5,
    totalTrades: 68,
    avgHold: '7.4d',
    since: 'Apr 2022'
  },
  {
    id: 'X',
    name: 'AUD/USD Carry',
    cls: 'forex',
    tagCls: 'tag-forex',
    tagLabel: 'Forex',
    risk: 2,
    color: '#9ec8ff',
    desc: 'Interest rate differential strategy on AUD/USD pair, combining carry trade principles with technical trend analysis. Optimized for capturing both directional moves and positive swap accumulation.',
    ytd: '+14.2%',
    ytdN: 14.2,
    allTime: '+68.4%',
    monthAvg: '+1.2%',
    maxDD: -7.2,
    sharpe: 2.5,
    winRate: 64,
    avgWin: '+2.2%',
    avgLoss: '-1.4%',
    profitFactor: 2.9,
    totalTrades: 76,
    avgHold: '12.6d',
    since: 'Jun 2022'
  },
  {
    id: 'XI',
    name: 'DAX Intraday',
    cls: 'indices',
    tagCls: 'tag-indices',
    tagLabel: 'Indices',
    risk: 3,
    color: '#c8b4ff',
    desc: 'Intraday trading strategy on German DAX index futures, focusing on European session volatility and key economic releases. Employs scalping techniques with strict time-based exits.',
    ytd: '+29.4%',
    ytdN: 29.4,
    allTime: '+148.6%',
    monthAvg: '+2.4%',
    maxDD: -13.2,
    sharpe: 2.0,
    winRate: 62,
    avgWin: '+1.8%',
    avgLoss: '-1.2%',
    profitFactor: 2.6,
    totalTrades: 234,
    avgHold: '0.4d',
    since: 'Jan 2022'
  },
  {
    id: 'XII',
    name: 'Copper Industrial',
    cls: 'commodities',
    tagCls: 'tag-commodities',
    tagLabel: 'Commodities',
    risk: 2,
    color: '#d4af37',
    desc: 'Fundamental-driven copper futures strategy tracking global industrial demand indicators and Chinese economic data. Combines macro analysis with technical entry/exit timing for medium-term positions.',
    ytd: '+18.6%',
    ytdN: 18.6,
    allTime: '+92.8%',
    monthAvg: '+1.5%',
    maxDD: -8.8,
    sharpe: 2.4,
    winRate: 60,
    avgWin: '+3.4%',
    avgLoss: '-1.8%',
    profitFactor: 2.8,
    totalTrades: 54,
    avgHold: '9.2d',
    since: 'May 2022'
  }
];
